name: kronik_hasta_takip
description: "Kronik hastaların takibi için mobil uygulama"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  fl_chart: ^0.64.0
  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.0
  smooth_page_indicator: ^1.1.0
  multi_select_flutter: 4.1.3
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/