// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTJy6BgD_mxR1nN1k4_2ienxllyz3Ghs',
    appId: '1:970623891525:web:f5046c4b7023ce8f554b2c',
    messagingSenderId: '970623891525',
    projectId: 'healthassistant-2e690',
    authDomain: 'healthassistant-2e690.firebaseapp.com',
    storageBucket: 'healthassistant-2e690.firebasestorage.app',
    measurementId: 'G-YL97G8HYV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD-j1O1ku8HXoQ8r9YKAaZH_6Pg51MuLo',
    appId: '1:970623891525:android:c86806cd9d56e85a554b2c',
    messagingSenderId: '970623891525',
    projectId: 'healthassistant-2e690',
    storageBucket: 'healthassistant-2e690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCw23dmcXnH-KQ7Sqh02kcE_0cMYD73TQ',
    appId: '1:970623891525:ios:8b99fa1a4b01f770554b2c',
    messagingSenderId: '970623891525',
    projectId: 'healthassistant-2e690',
    storageBucket: 'healthassistant-2e690.firebasestorage.app',
    iosBundleId: 'com.example.kronikHastaTakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCw23dmcXnH-KQ7Sqh02kcE_0cMYD73TQ',
    appId: '1:970623891525:ios:8b99fa1a4b01f770554b2c',
    messagingSenderId: '970623891525',
    projectId: 'healthassistant-2e690',
    storageBucket: 'healthassistant-2e690.firebasestorage.app',
    iosBundleId: 'com.example.kronikHastaTakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoTJy6BgD_mxR1nN1k4_2ienxllyz3Ghs',
    appId: '1:970623891525:web:caf10fe8257e5e73554b2c',
    messagingSenderId: '970623891525',
    projectId: 'healthassistant-2e690',
    authDomain: 'healthassistant-2e690.firebaseapp.com',
    storageBucket: 'healthassistant-2e690.firebasestorage.app',
    measurementId: 'G-9M4VVCH1FS',
  );
}
